# Generated by Django 2.0.4 on 2018-04-22 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=20000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('rating', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=2000)),
                ('type', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_name', models.CharField(max_length=200)),
                ('end_name', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ubertravel.Event')),
            ],
            bases=('ubertravel.event',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ubertravel.Event')),
                ('price', models.IntegerField(default=20)),
                ('cuisine', models.CharField(max_length=200)),
            ],
            bases=('ubertravel.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubertravel.City'),
        ),
        migrations.AddField(
            model_name='attractiontag',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubertravel.Attraction'),
        ),
    ]
