# Generated by Django 2.0.4 on 2018-04-21 21:30

from django.db import migrations
# from ubertravel.fillDatabase import addAttractions, addRestaurants, addTravelTimes, add_cities
from datetime import datetime, timedelta
from geopy.geocoders import Nominatim
import googlemaps, json


def some_func(apps, schema_editor):
    City = apps.get_model('ubertravel', 'City')
    Event = apps.get_model('ubertravel', 'Event')
    Restaurant = apps.get_model('ubertravel', 'Restaurant')
    Attraction = apps.get_model('ubertravel', 'Attraction')
    TravelTime = apps.get_model('ubertravel', 'TravelTime')

    add_cities("../CityData/Hong Kong_attractions.json", City)
    add_restaurants("../CityData/Hong Kong_restaurants.json", Restaurant, City)
    add_attractions("../CityData/Hong Kong_attractions.json", Attraction, City)
    addTravelTimes("Hong Kong", Event, TravelTime, Attraction, Restaurant,City)


class Migration(migrations.Migration):

    dependencies = [
        ('ubertravel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(some_func)
    ]
